apiVersion: v1
kind: PersistentVolume
metadata:
  name: rmq-datadir-2
  labels:
    app: rmq
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pods/rmq-2/datadir

