---
# tasks file for haproxy

- name: install haproxy
  apt:
    name: haproxy
    state: present

- name: install keepalived
  apt:
    name: keepalived
    state: present

- name: configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: Start keepalived
  service:
    name: keepalived
    state: started
    enabled: yes

- name: Copy SSL Cert to haproxy
  copy:
    src: hawaiiantel.com.crt
    dest: /etc/ssl/private/hawaiiantel.com.crt
    mode: u=rw,g=r,o=r
  tags:
    haproxy-config

- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  tags:
    haproxy-config

- name: Configure SPOP
  template:
    src: spoe-modsecurity.conf.j2
    dest: /etc/haproxy/spoe-modsecurity.conf
  tags:
    haproxy-config

- name: Restart haproxy
  service:
    name: haproxy
    state: restarted
  tags:
    haproxy-config


